-- I am presented with the following options: 
-- view all departments, 
-- view all roles, 
-- view all employees, 
-- add a department, 
-- add a role, 
-- add an employee, and 
-- update an employee role
-- * BONUS: Update employee managers.
-- * BONUS: View employees by manager.
-- * BONUS: View employees by department.
-- * BONUS: Delete departments, roles, and employees.
-- * BONUS: View the total utilized budget of a department&mdash;
-- in other words, the combined salaries of all employees in that department.